discord:
  profiles:
    - name: имя | maxrbv
      token: токен | asdasdasd234234
      channel_id: id канала | 37491294124
      messages: имя txt файла с | messages.txt
      timeout: пауза между сообщениями | 300
      proxy: прокси | 'http://юзер:пароль@ip:порт'
    - name: имя | maxrbv
      token: токен | asdasdasd234234
      channel_id: id канала | 37491294124
      messages: имя txt файла с | messages.txt
      timeout: пауза между сообщениями | 300
      proxy: прокси | 'http://юзер:пароль@ip:порт'